name: paged_vertical_calendar_example
description: A simple example showing several ways this package can be used to implement calendar related interfaces.
homepage: https://github.com/casvanluijtelaar/paged_vertical_calendar.git
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  paged_vertical_calendar:
    path: ../
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
